### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by dturton**
missing function declaration: function apache_request_headers()

### CODE REVIEW

**Comment by surrealroad** [comment]
well spotted, thanks.

**Comment by dturton** [comment]
any idea why safari wouldn’t be prompting me for push notifications on my dev site? if you can take a look that would be great.. www.etrivo.com

thanks,
David
On Oct 25, 2013, at 12:26 PM, surrealroad notifications@github.com wrote:

well spotted, thanks.

**Comment by surrealroad** [comment]
Try adding https://www.etrivo.com to the list of allowed domains.

**Comment by dturton** [comment]
thanks that did it.. I was going crazy…

On Oct 25, 2013, at 12:44 PM, surrealroad notifications@github.com wrote:

Try adding https://www.etrivo.com to the list of allowed domains.

**Pull request merged**
